### ISSUE TITLE
Offline to online Ingestion Job on Dataproc fails due to missing method

### ISSUE THREAD

**Issue by beatgeek** [feast-dev/feast-spark#42]
Running a Spark job on Dataproc using debian10 image `Spark 3.1.1-rc1` and `Scala 2.12.13`on submission the logs show:

```
21/03/09 20:06:52 WARN org.apache.spark.SparkConf: The configuration key 'spark.yarn.user.classpath.first' has been deprecated as of Spark 1.3 and may be removed in the future. Please use spark.{driver,executor}.userClassPathFirst instead.
21/03/09 20:06:52 WARN org.apache.spark.SparkConf: The configuration key 'spark.yarn.user.classpath.first' has been deprecated as of Spark 1.3 and may be removed in the future. Please use spark.{driver,executor}.userClassPathFirst instead.
Exception in thread "main" java.lang.NoSuchMethodError: org.json4s.ShortTypeHints.<init>(Lscala/collection/immutable/List;)V
	at feast.ingestion.IngestionJob$.<init>(IngestionJob.scala:30)
	at feast.ingestion.IngestionJob$.<clinit>(IngestionJob.scala)
	at feast.ingestion.IngestionJob.main(IngestionJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1030)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```
When no SPARK_INGESTION_JAR is set this one is used `https://storage.googleapis.com/feast-jobs/spark/ingestion/feast-ingestion-spark-develop.jar` 

The error relates to the use of a method in the IngestionJob.scala code (see below reference):

https://github.com/feast-dev/feast-spark/blob/f3c4dd874f53b4f6227eed32aea3d7c6888bc58e/spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala#L30

Looking at the jar file (`feast-ingestion-spark-develop`) , I can see there is indeed no method `List` only `LazyList`:

```
scala/collection/compat/immutable/ArraySeq$$anon$1.class
scala/collection/compat/immutable/ArraySeq$.class
scala/collection/compat/immutable/ArraySeq$ofBoolean.class
scala/collection/compat/immutable/ArraySeq$ofByte.class
scala/collection/compat/immutable/ArraySeq$ofChar.class
scala/collection/compat/immutable/ArraySeq$ofDouble.class
scala/collection/compat/immutable/ArraySeq$ofFloat.class
scala/collection/compat/immutable/ArraySeq$ofInt.class
scala/collection/compat/immutable/ArraySeq$ofLong.class
scala/collection/compat/immutable/ArraySeq$ofRef.class
scala/collection/compat/immutable/ArraySeq$ofShort.class
scala/collection/compat/immutable/ArraySeq$ofUnit.class
scala/collection/compat/immutable/ArraySeq.class
scala/collection/compat/immutable/LazyList$$anon$1.class
scala/collection/compat/immutable/LazyList$$anon$2.class
scala/collection/compat/immutable/LazyList$$hash$colon$colon$.class
scala/collection/compat/immutable/LazyList$.class
scala/collection/compat/immutable/LazyList$Deferrer$.class
scala/collection/compat/immutable/LazyList$Deferrer.class
scala/collection/compat/immutable/LazyList$LazyBuilder$.class
scala/collection/compat/immutable/LazyList$LazyBuilder$DeferredState.class
scala/collection/compat/immutable/LazyList$LazyBuilder.class
scala/collection/compat/immutable/LazyList$LazyIterator.class
scala/collection/compat/immutable/LazyList$LazyListCanBuildFrom.class
scala/collection/compat/immutable/LazyList$SerializationProxy.class
scala/collection/compat/immutable/LazyList$SerializeEnd$.class
scala/collection/compat/immutable/LazyList$SlidingIterator.class
scala/collection/compat/immutable/LazyList$State$.class
scala/collection/compat/immutable/LazyList$State$Cons.class
scala/collection/compat/immutable/LazyList$State$Empty$.class
scala/collection/compat/immutable/LazyList$State.class
scala/collection/compat/immutable/LazyList$WithFilter.class
scala/collection/compat/immutable/LazyList$cons$.class
scala/collection/compat/immutable/LazyList.class
```

I also checked the `pom.xml` and I see the compatible json4s-native jar is reference.
Open to ideas on how to resolve this.

**Comment by beatgeek** [comment]
Looking a bit more at this line: https://github.com/feast-dev/feast-spark/blob/f3c4dd874f53b4f6227eed32aea3d7c6888bc58e/spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala#L21

I think the issue could be that this is that the json4 jar isn't on the cluster. I don't think it's expected that I would need to load json4 jar? 

My other idea is to modify the import to:
```
import org.json4s.JsonDSL._
import org.json4s._
import org.json4s.native.JsonMethods._

implicit val formats = DefaultFormats
```

**Comment by pyalex** [comment]
Hi @beatgeek, we currently on Spark 3.0.1 (see https://github.com/feast-dev/feast-spark/blob/master/pom.xml#L20). Ingestion jar is built against this version and since `json4s` is also installed as spark dependency, I didn't include it to avoid conflicts.
Appropriate Dataproc version (which we use in e2e tests) is `2.0.0-RC21-debian10`. You can create cluster with this images using cli: `gcloud dataproc clusters create cluster-name --image-version='2.0.0-RC21-debian10'`

**Comment by beatgeek** [comment]
Hi @pyalex - Thanks for the information and now I see it in the pom. I appreciate it and will stand up a cluster with this image.
